from bot.utilities.constants import KEYS


CREATOR_TELEGRAM_ID: int = int(KEYS.CREATOR_TELEGRAM_ID)

MAX_TEXT_LENGTH: int = 3900
MAX_CAPTION_LENGTH: int = 900

PROGRESS_BAR_PERIOD: int = 20


CONTROL_PANEL: str = (
    "*Control panel*\n"
    "_creator-only access_\n"
    "\n"
    "_{} — required, [] — optional_\n"
    "\n"
    "*stats*\n"
    "/users\n"
    "\n"
    "*cleaning*\n"
    "/clear\n"
    "/drop {\n"
        "\t\t\t{\n"
            "\t\t\t\t\t\t\[ guards ]\n"
            "\t\t\t\t\t\t\[ me ]\n"
            "\t\t\t\t\t\t\[ all ]\n"
            "\t\t\t\t\t\t\[ groups ]\n"
            "\t\t\t\t\t\t\[ compacts ]\n"
            "\t\t\t\t\t\t\[ bb ]\n"
        "\t\t\t}\n"
        "\t\t\t\[ message: {} ]\n"
    "}\n"
    "\n"
    "*others*\n"
    "/broadcast {\n"
        "\t\t\t{ users: {\n"
            "\t\t\t\t\t\t\[ user-id&… ]\n"
            "\t\t\t\t\t\t\[ me ]\n"
            "\t\t\t\t\t\t\[ all ]\n"
            "\t\t\t\t\t\t\[ groups ]\n"
            "\t\t\t\t\t\t\[ compacts ]\n"
            "\t\t\t\t\t\t\[ bb ]\n"
        "\t\t\t} }\n"
        "\t\t\t\[ signed: false ]\n"
        "\t\t\t{ message: {} }\n"
        "\n"
        "\t\t\tEntities to broadcast:\n"
        f"\t\t\t• message — up to {MAX_TEXT_LENGTH} characters in length.\n"
        f"\t\t\t• photo — with caption up to {MAX_CAPTION_LENGTH} characters in length.\n"
        f"\t\t\t• audio — in the .MP3 or .M4A format, with caption up to {MAX_CAPTION_LENGTH} characters in length.\n"
        f"\t\t\t• video — in the .MP4 format, up to 50 MB in size, with caption up to {MAX_CAPTION_LENGTH} characters in length.\n"
        f"\t\t\t• document — up to 50 MB in size, with caption up to {MAX_CAPTION_LENGTH} characters in length.\n"
        "\n"
    "}\n"
    "/daysoff {\n"
        "\t\t\t\[ list ]\n"
        "\t\t\t\[ add: { dd-mm } ]\n"
        "\t\t\t\[ message: {} ]\n"
        "\t\t\t\[ drop: {\n"
            "\t\t\t\t\t\t\[ dd-mm ]\n"
            "\t\t\t\t\t\t\[ all ]\n"
        "\t\t\t} ]\n"
    "}\n"
    "/donated {\n"
        "\t\t\tamount: {}\n"
        "\t\t\tdate: { yyyy-mm-dd }\n"
        "\t\t\tdonator: {}\n"
    "}\n"
    "\n"
    "*hashtags*\n"
    "# users\n"
    "# metrics\n"
    "# data\n"
    "# cleared\n"
    "# erased\n"
    "# dropped\n"
    "# broadcast\n"
)


USERS_STATS: str = (
    "*Users*\n"
    "_stats of #users_\n"
    "\n"
    "*platforms*\n"
    "• telegram: {telegram}\n"
    "• vk: {vk}\n"
    "\n"
    "*types*\n"
    "• groups: {groups}\n"
    "• compact: {compact}\n"
    "• bb: {bb}\n"
    "\n"
    "*states*\n"
    "• setup: {setup}\n"
    "• unsetup: {unsetup}\n"
    "\n"
    "*{total}* users in total!"
)


BROADCAST_MESSAGE_TEMPLATE: str = (
    "*Телеграмма от разработчика*\n"
    "#broadcast\n"
    "\n"
    "{broadcast_message}\n"
    "\n"
    "• Поддержать бота: /donate\n"
    "• Написать разработчику: @airatk\n"
    "• Подписаться на разработчика: instagram.com/airatk.inst\n"
)
