from enum import Enum


class Commands(Enum):
    CREATOR = "creator"
    USERS = "users"
    METRICS = "metrics"
    DATA = "data"
    CLEAR = "clear"
    ERASE = "erase"
    DROP = "drop"
    GUARDDROP = "guarddrop"
    BROADCAST = "broadcast"
    REVERSE = "reverse"
    
    CANCEL = "cancel"
    START = "start"
    
    LOGIN = "login"
    LOGIN_EXTENDED = "login-extended"
    LOGIN_COMPACT = "login-сompact"
    LOGIN_SET_INSTITUTE = "login-set-institute-"
    LOGIN_SET_YEAR = "login-set-year-"
    LOGIN_SET_GROUP = "login-set-group-"
    LOGIN_SET_NAME = "login-set-name-"
    LOGIN_SET_CARD = "login-set-card"
    UNLOGIN = "un-login"
    
    CLASSES = "classes"
    EXAMS = "exams"
    
    LECTURERS = "lecturers"
    LECTURERS_NAME = "lecturers-name"
    
    SCORE = "score"
    SCORE_SEMESTER = "score-semester"
    SCORE_ALL = "score-all"
    SCORE_EXAMS = "score-exams"
    SCORE_TESTS = "score-test"
    SCORE_GRADED_TESTS = "score-graded-test"
    
    NOTES = "notes"
    NOTES_ADD = "notes-add"
    NOTES_SHOW = "notes-show"
    NOTES_SHOW_ALL = "notes-show-all"
    NOTES_DELETE = "notes-delete"
    NOTES_DELETE_ALL = "notes-delete-all"
    
    EDIT = "edit"
    EDIT_ADD = "edit-add"
    EDIT_WEEKTYPE = "edit-weektype"
    EDIT_WEEKDAY = "edit-weekday"
    EDIT_TIME = "edit-time"
    EDIT_BUILDING = "edit-building"
    EDIT_AUDITORIUM = "edit-auditorium"
    EDIT_SUBJECT_TITLE = "edit-subject-title"
    EDIT_SUBJECT_TYPE = "edit-subject-title"
    EDIT_LECTURER = "edit-lecturer-name"
    EDIT_DEPARTMENT = "edit-department"
    EDIT_SHOW = "edit-show"
    EDIT_SHOW_ALL = "edit-show-all"
    EDIT_SHOW_WEEKTYPE = "edit-show-weektype"
    EDIT_SHOW_WEEKDAY = "edit-show-weekday"
    EDIT_SHOW_EDIT = "edit-show-edit"
    EDIT_DELETE = "edit-delete"
    EDIT_DELETE_ALL = "edit-delete-all"
    EDIT_DELETE_WEEKTYPE = "edit-delete-weektype"
    EDIT_DELETE_WEEKDAY = "edit-delete-weekday"
    EDIT_DELETE_EDIT = "edit-delete-edit"
    
    LOCATIONS = "locations"
    
    WEEK = "week"
    CARD = "card"
    BRS = "brs"
    HELP = "help"
    DONATE = "donate"
    ME = "me"
    
    UNKNOWN = "unknown"
